# Accelerate config cho 1× A100 80GB (RunPod default)

compute_environment: LOCAL_MACHINE
distributed_type: NO
mixed_precision: bf16
num_processes: 1
num_machines: 1
machine_rank: 0
gpu_ids: "0"
main_process_ip: null
main_process_port: null
rdzv_backend: static
same_network: true
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
debug: false
